a = "is string"
print(a.upper())
print(a.lower())
print(a.rstrip('g'))
print(a.lstrip('is'))
print(a.capitalize())
print(a.split(' '))
print(a.replace(' ', "space"))
print(a.center(50))
print(a.count('s'))
print(a.startswith('is') and a.endswith('pg'))
print(a.endswith('ng'))
print(a.find(' '))
print(a.index('s'))
print(a.rindex('s'))
print(a.isalnum())
print(a.islower())
print(a.isalpha())
print(a.isprintable())
print(a.isupper())
print(a.isspace())
print(a.title())
print(a.swapcase())
