lst = [1, 2, 4, 5, 6, 2, 3, 6]
print(lst)
lst.append(10)
lst.sort(reverse=True)
lst.reverse()
lst.insert(2, 20)
lst.remove(6)
lst.pop()
lst.extend([1, 2, 3])
difflst = lst.copy()
print(lst.index(2))
print(lst.count(2))
print(lst)
print(difflst)
